name: To_Know_Me
description: Social networking application made with a flutter whose main idea is to facilitate communication and acquaintance with people and to build a strong communication network.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.3.0
  conditional_builder_null_safety: ^0.0.6
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.6
  hexcolor: ^3.0.1
  fluttertoast: ^8.1.2
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6
  flutter_native_splash: ^2.2.16
  liquid_swipe: ^3.0.0
  social_share: ^2.3.1
  #firebase
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  cloud_firestore: ^4.3.0
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.2.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/light_icon.png
  color_dark: "#1a1a1a"
  image_dark: assets/icons/dark_icon.png
  android: true
  #ios: true
  #android_gravity: fill
  #ios_content_mode: scaleAspectFill

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: true
  #  ios: true
  image_path: "assets/icons/chat1.png"
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: myFont
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf